name: solitaire
description: "Collection of card games"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  adaptive_action_sheet: ^2.0.3
  collection:
  confetti: ^0.8.0
  equatable: ^2.0.7
  flutter_hooks: ^0.21.1-pre.4
  flutter_svg: ^2.0.17
  intl: ^0.18.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.0+3

  utils:
    git:
      url: https://github.com/JLogical-Apps/flood
      ref: v4.3
      path: packages/utils/utils

  card_game:
    path: ../cards

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons: # dart run flutter_launcher_icons
  android: "launcher_icon"
  ios: true
  image_path: "assets/cards.png"
  min_sdk_android: 21
  web:
    generate: true